---
# tasks file for jira


- name: Check for OS support
  fail: msg="OS is not supported"
  when: ansible_os_family != 'RedHat'


- name: Create jira group
  group: name={{ jira_group }} gid={{ jira_gid }} state=present

- name: Create jira user
  user: name={{ jira_user }} uid={{ jira_uid }} group={{ jira_group }} shell=/bin/bash state=present

- name: Create jira install dir
  file: path={{ jira_installto }} state=directory owner={{ jira_user }} group={{ jira_group }} mode=0755

- name: Create jira data dir
  file: path={{ jira_datadir }} state=directory owner={{ jira_user }} group={{ jira_group }} mode=0755

- name: Create jira_home_dir
  file: path={{ jira_home_dir }} state=directory owner={{ jira_user }} group={{ jira_group }} mode=0755

- name: get installer
  get_url:
    url={{ jira_baseurl }}/{{ jira_installer }}
    dest={{ jira_tmp }}/{{ jira_installer }}
  tags: install


- name: Extract installation
  shell: tar xvf {{ jira_tmp }}/{{ jira_installer }} -C {{ jira_installto }} --transform='s#\(atlassian\)-#\1/#'
  #when: fetch.changed
  tags: install

- name: Ensure consistent file ownership
  file: path={{ jira_installto }}/atlassian/jira-software-{{ jira_version }}-standalone recurse=true
        owner={{ jira_user }} group={{ jira_user }}

- name: Ensure data dir exists
  file: path={{ jira_datadir }} state=directory
        owner={{ jira_user }} group={{ jira_user }}

- name: Set data dir in tomcat config
  lineinfile:
    dest={{ jira_installto }}/atlassian/jira-software-{{ jira_version }}-standalone/atlassian-jira/WEB-INF/classes/jira-application.properties
    regexp="^jira.home"
    line="jira.home={{ jira_datadir }}"
    state=present
  tags: install

- name: Ensure logs symlink exists
  file: src={{ jira_installto }}/atlassian/jira-software-{{ jira_version }}-standalone/logs
        path=/var/log/jira
        state=link
  tags: install

- name: Add service
  template: src=jira.j2 dest=/etc/init.d/jira
            owner=root group=root mode=0755
  tags: install

-  name: Configure database connection
   template:
    src: dbconfig.xml.j2
    dest: "{{ jira_home_dir }}/dbconfig.xml"
    mode: 0644
    owner: "{{ jira_user }}"
    group: "{{ jira_group }}"

- name: enable service
  service:
    name: "jira"
    enabled: "yes"
  
